name: Simple Task Report form
description: Simple Task Report form
title: "[simple-task]: <title>"
labels: ["simple-task"]
body:
  - type: markdown
    attributes:
      value: |
        > Please fill out this simple task report form and click `Submit new issue` button at the bottom.
        
        > Remember to add a proper title related with this simple task.
  - type: dropdown
    id: sub-services
    attributes:
      label: Components
      description: Multiple component selection
      multiple: true
      options:
        - All
        - Developer Environment
        - Identity-platform-initialiser
        - RS
        - UI
        - RCS
        - IG
        - Spring Config
        - Identity Client library
        - Model library
        - Common library
        - Dev Operations
        - Functional Tests
  - type: textarea
    id: sub-story
    attributes:
      label: Task Story (optional)
      value: As the [developer], I want to [do something] so that [comply with the achievement].
      placeholder: |
        As the [developer], I want to [do something] so that [comply with the achievement].
  - type: textarea
    id: sub-description
    attributes:
      label: Describe de task
      description: A clear and concise description of what the task is.
      placeholder: |
        A clear and concise description of what the subtask is.
    validations:
      required: true
  - type: textarea
    id: sub-criteria
    attributes:
      label: Acceptance criteria
      description: Conditions that a subtask must satisfy to be accepted.
    validations:
      required: true
  - type: textarea
    id: sub-additional
    attributes:
      label: Additional Context (optional)
      description: Add any other context about the subtask here.
  - type: textarea
    id: sub-code-analysis
    attributes:
      label: Code solution approach (optional)
      description: If you already investigated the code, please share your solution approach here.
